### ISSUE TITLE
【BUG】完成扫描之后输入“gbot login”插件未经行登录

### ISSUE THREAD

**Issue by KaRuichin** [CSPDevTeam/CSPGuildBot#1]
![image](https://user-images.githubusercontent.com/69111766/184535125-3ec4a73f-af02-4f4c-b059-d19ce36be29a.png)

如图，我在正常扫码并在手机确认登录之后控制台输入`gbot login`并回车之后并没有任何反应，在`手机QQ`-`设置`-`账号安全`-`登录设备管理`中也没有发现新增的设备。

**Comment by HuoHuas001** [comment]
可以打开gbot qrcode然后关掉试试看

**Comment by HuoHuas001** [comment]
目前我也不知道是什么个问题导致他不响应

**Comment by KaRuichin** [comment]
> 目前我也不知道是什么个问题导致他不响应

疑似所有`gbot`指令都没有响应，甚至`gbot help`也是（

**Comment by HuoHuas001** [comment]
可能是bds的问题，据我所知Windows终端好像有点问题

**Comment by KaRuichin** [comment]
> 可能是bds的问题，据我所知Windows终端好像有点问题

![image](https://user-images.githubusercontent.com/69111766/184535371-2c9bc96d-5bf5-4485-8779-94d01eefbda1.png)
在`命令提示符`的表现和`Windows 终端`中一样（输入任何`gbot`指令都没有响应）

**Comment by HuoHuas001** [comment]
把LiteLoader.json的ForceUtf8Input的enable改成true试试看

**Comment by KaRuichin** [comment]
> 把LiteLoader.json的ForceUtf8Input的enable改成true试试看

![image](https://user-images.githubusercontent.com/69111766/184535524-29cc27f5-e10f-4466-963e-da0a2dfdd141.png)
在前面的几条测试中都一直是这个状态。

**Comment by HuoHuas001** [comment]
那试试看关掉呢

**Comment by KaRuichin** [comment]
> 那试试看关掉呢

还是也不行

**Comment by HuoHuas001** [comment]
使用powershell呢

**Comment by KaRuichin** [comment]
> 

不行，这次还重置了一下`LiteLoader.json`（重新生成）

**Comment by HuoHuas001** [comment]
那就没啥方法了

**Comment by KaRuichin** [comment]
那请问如果使用账号+密码登录的时候，完成滑块验证获取到的ticket用什么指令输入？

**Comment by HuoHuas001** [comment]
gbot ticket "<ticket>"

**Comment by KaRuichin** [comment]
本插件疑似和“[mine - 刷矿机！](https://www.minebbs.net/resources/mine.1626/)”冲突，当我卸载“[mine - 刷矿机！](https://www.minebbs.net/resources/mine.1626/)”之后重新运行一切正常，包括扫码登录。

**Comment by HuoHuas001** [comment]
mine老版本了，建议使用提米的

**Comment by KaRuichin** [comment]
> mine老版本了，建议使用提米的

好的，谢谢大佬 >_<
